services:
  app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    entrypoint: /bin/sh -c "
      trap exit TERM;
      certbot certonly --webroot --webroot-path=/var/www/html --email nikitos19735@yandex.ru --agree-tos --no-eff-email -d fastapi.mwx.su;
      while :; do
        certbot renew --webroot --webroot-path=/var/www/html;
        nginx -s reload;
        sleep 12h & wait $${!};
      done"


volumes:
  www-html:
  etc-letsencrypt:

networks:
  app:
    driver: bridge